### PR TITLE
Add navigation and hopefully fix code block.

### PR DESCRIPTION
**Pull request by will-in-wi**
Requested fix for https://github.com/capistrano/documentation/issues/150.

I'm not sure I fixed the code block. I'm messing with ways of testing this. Same for the link. Comments on either, and the text of the link would be appreciated.

### CODE REVIEW

**Comment by mattbrictson** [comment]
Let me see if I can get a local Jekyll environment up and running to test this.

**Comment by mattbrictson** [comment]
Looks like you need to put the code in a "bash" block like this to get the code formatting to work properly:

`````` diff
 Files commited to version control (i.e. not in .gitignore) can still be ignored when deploying.  To ignore these files or directories, simply add them to .gitattributes:

-    config/deploy/deploy.rb   export-ignore
-    config/deploy/            export-ignore
+```bash
+config/deploy/deploy.rb   export-ignore
+config/deploy/            export-ignore
+```

 These files will be kept in version control but not deployed to the server.
``````

**Comment by mattbrictson** [comment]
BTW you should be able to test locally like this:

```
$ bundle install
$ bundle exec jekyll serve
...
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
```

**Comment by will-in-wi** [comment]
Thanks, I made the correction and was able to test locally.

**Comment by mattbrictson** [comment]
Could you rebase this down to a single commit?

**Comment by will-in-wi** [comment]
Commits squashed.

**Comment by mattbrictson** [comment]
:raised_hands:

**Pull request merged**
