### PR TITLE
Document new option `svn_revision`

### PR DESCRIPTION
**Pull request by marcovtwout**

### CODE REVIEW

**Comment by leehambley** [comment]
Since this depends on a modern version of Capistrano can we document the version that it was introduced please?

**Comment by marcovtwout** [comment]
This currently only works for 'master', so what should be this next version? :)

**Comment by leehambley** [comment]
We don't know yet :)

**Comment by marcovtwout** [comment]
It was introduced in https://github.com/capistrano/capistrano/commit/012929eb926cbd5d9be456b7cdd9120e1f04bc60, is that what you mean?

**Comment by mattbrictson** [comment]
Just prefix it with **New in Capistrano 3.5** for now. We probably won't merge until the next version is released, so there will be an opportunity to change it once we actually choose the final version number.

**Comment by mattbrictson** [comment]
Thanks. I'll merge this once 3.5.0 has been released.

**Comment by will-in-wi** [comment]
Given that other commits (https://github.com/capistrano/documentation/pull/175/files) are referencing 3.5.0, does it make sense to merge this now?

**Pull request merged**
