### PR TITLE
Server and role properties

### PR DESCRIPTION
**Pull request by townsen**
In a bid to clarify the recent confusion around using both 'server' and 'role' declarations at the same time I've done a lot of work on the documentation.

The core problem -- that using :user and :port specifiers on a host causes multiple servers to be created remains. As it is explicitly called out in the tests I think it was originally intended as a feature. However I don't think that this is what should be done. I think that hosts should certainly not be distinguished by their SSH port - I can't think of a legitimate reason why a single server would have more than one SSHD running! I can imagine that at in different tasks the SSH user might need to change, and I've an internal piece of code that enables me to do that. So I vote that multiple definitions of a server should be merged based on hostname/ip address. This would fit the paradigm of Custom Property merging.

Any ideas? I am preparing a branch to implement this, but won't continue unless we're in agreement. I don't need this for my own purposes - we never specify either user or port at the server or role level, so I've never noticed it until now!!

### CODE REVIEW

**Comment by leehambley** [comment]
I also agree (I wrote the test) that it causes more problems than it
solves, as for multiple SSH daemons, I've been in places where a gateway
runs proxies to different back end severs :20001.. Server #1, and so on....
But that usecase can be solved with SSH config, or a hosts file entry

**Comment by Kriechi** [comment]
PR looks good.

One question about the code-tags: Did you change them on purpose?
Did you have problems with `{ highlight ruby }` - or why did you switch to the three-backtick syntax?
I would like to keep the usage the same across all files - unless there is a good reason (better html? nicer CSS?).

**Comment by leehambley** [comment]
I can't remember why, but I think before it was a GH pages thing, the `{highlight: ruby}` was the only way to get it to look right, we can simply pick one and find/replace and stick with it though, now that we're on GH pages.

**Comment by Kriechi** [comment]
:+1: 
three-backticks is IMHO more common in a Markdown-Github-environment.

@townsen you want to add that?
or should I do it after this PR is merged?

**Comment by townsen** [comment]
I used back-ticks as the other syntax caused the formatting to break. Also I do think they are more common. I'll update the PR later today to make them all consistent. 

Regarding the user:port simplification - I'll get a PR out for that Monday or Tuesday (Pacific!)

**Comment by leehambley** [comment]
Thanks you guys

**Comment by townsen** [comment]
Ok, I changed all to back-ticks. During my inspection of the doc to make sure that nothing was broken I also found and fixed some typos and errors that I'd missed earlier.

Don't forget that this will need PR #1360 in Capistrano to get the `role_properties()` method.

I'll create the other PR during the 'work week'

**Comment by leehambley** [comment]
Thanks again @townsen

**Pull request merged**
