### PR TITLE
Upgrade to Jekyll 3 and switch from pygments to rouge to fix GH Pages warning

### LINKED ISSUE #168: GitHub Pages emits warning about syntax highlighter
> You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml'. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.

### PR DESCRIPTION
**Pull request by mattbrictson**
Fixes #168 

I found out that `jekyll serve` would not work with rouge unless I first upgraded to the latest version of Jekyll. So I did. I did a quick visual test and the Jekyll 3 site seems to render identically to the Jekyll 2 version.

The following gems were upgraded:

```
activesupport             4.2.0   → 4.2.5.1
addressable               (new)   → 2.3.8
blankslate                2.1.2.4 → (removed)
celluloid                 0.16.0  → (removed)
classifier-reborn         2.0.3   → (removed)
coffee-script             2.3.0   → 2.4.1
coffee-script-source      1.8.0   → 1.10.0
ethon                     (new)   → 0.8.1
execjs                    2.2.2   → 2.6.0
faraday                   (new)   → 0.9.2
fast-stemmer              1.0.2   → (removed)
ffi                       1.9.6   → 1.9.10
github-pages              32      → 45
github-pages-health-check 0.2.1   → 0.6.0
hitimes                   1.2.2   → (removed)
html-pipeline             1.9.0   → 2.3.0
jekyll                    2.4.0   → 3.0.2
jekyll-feed               (new)   → 0.3.1
jekyll-gist               1.1.0   → 1.4.0
jekyll-mentions           0.2.1   → 1.0.0
jekyll-redirect-from      0.6.2   → 0.9.1
jekyll-sass-converter     1.2.0   → 1.3.0
jekyll-seo-tag            (new)   → 0.1.4
jekyll-sitemap            0.6.3   → 0.10.0
jekyll-textile-converter  (new)   → 0.1.0
jekyll-watch              1.2.0   → 1.3.1
jemoji                    0.4.0   → 0.5.1
json                      1.8.2   → 1.8.3
kramdown                  1.5.0   → 1.9.0
liquid                    2.6.1   → 3.0.6
listen                    2.8.5   → 3.0.5
maruku                    0.7.0   → (removed)
mini_portile              0.6.2   → (removed)
mini_portile2             (new)   → 2.0.0
minitest                  5.5.1   → 5.8.4
multipart-post            (new)   → 2.0.0
nokogiri                  1.6.5   → 1.6.7.2
octokit                   (new)   → 4.2.0
parslet                   1.5.0   → (removed)
posix-spawn               0.3.9   → (removed)
public_suffix             1.4.6   → 1.5.3
pygments.rb               0.6.0   → (removed)
rb-fsevent                0.9.4   → 0.9.7
rb-inotify                0.9.5   → 0.9.6
rdiscount                 2.1.7   → 2.1.8
redcarpet                 3.1.2   → 3.3.3
rouge                     (new)   → 1.10.1
sass                      3.4.10  → 3.4.21
sawyer                    (new)   → 0.6.0
terminal-table            1.4.5   → 1.5.2
thread_safe               0.3.4   → 0.3.5
timers                    4.0.1   → (removed)
toml                      0.1.2   → (removed)
typhoeus                  (new)   → 0.8.0
yajl-ruby                 1.1.0   → (removed)
```

### CODE REVIEW

**Comment by mattbrictson** [comment]
@leehambley or @will-in-wi, can you double-check that my branch still builds for you locally so that I can pull the trigger on this PR? Thanks!

**Comment by will-in-wi** [comment]
I can't get `bundle install` to work…

```
Gem::RemoteFetcher::FetchError: bad response Forbidden 403 (https://rubygems.global.ssl.fastly.net/gems/rb-inotify-0.9.6.gem)
```

```
⚡ gem install rb-inotify -v '0.9.6'
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/rb-inotify-0.9.6.gemspec.rz)
```

I'm trying to figure out how to point to a different mirror.

**Comment by will-in-wi** [comment]
Okay, switched to another mirror and got it building. The site looks decent overall. However, some syntax highlighting looks off. For example, on http://localhost:4000/documentation/overview/what-is-capistrano/

screenshot 2016-02-08 18 32 11

The fonts have changed slightly. The live site has a heavier weight. I don't think this is an issue, just to note.

Other than that, it looks good.

**Comment by will-in-wi** [comment]
Correction, I got my wires crossed and the syntax highlighting thing I saw is the same on the live site.

**Comment by mattbrictson** [comment]
OK, thanks! Just curious, how did you switch your rubygems mirror?

**Comment by will-in-wi** [comment]
I changed the source declaration. I used some random RedHat mirror I found in some post somewhere on the web. I'm sure it was safe. :)

**Comment by mattbrictson** [comment]
Ah, good call. :)

**Pull request merged**
