### PR TITLE
Document new SCM plugin system

### PR DESCRIPTION
**Pull request by mattbrictson**
This is the corresponding documentation for the new SCM plugin system implemented here: https://github.com/capistrano/capistrano/pull/1572

### CODE REVIEW

**Comment by leehambley** [comment]
Do you think we should look at a 3.6x release of Cap to introduce this sooner, rather than later? I know that the plugin code is in 3.5.x (nice work, again btw) but specifically the SCM plugin example isn't out there yet (well, not even merged yet!) -- should we hold off on merging this ?

**Comment by mattbrictson** [comment]
Yes, let's wait until 3.6 before merging this.

**Comment by mattbrictson** [comment]
Rebased.

**Comment by leehambley** [comment]
Thanks matt, were we still waiting to merge this around 3.6 ?

**Comment by mattbrictson** [comment]
Yes, capistrano/capistrano#1572 needs to be merged and released before merging this documentation PR. No rush.

**Comment by mattbrictson** [comment]
Closed in favor of https://github.com/capistrano/capistrano/pull/1767

**Pull request closed without merging**
